@echo off
echo Starting the Digital Aptitude backend server...
start cmd /k "pip install -r requirements.txt && python api\index.py || pause"
echo Waiting for server to start...
ping 127.0.0.1 -n 5 > nul
echo Opening the frontend in your browser...
start index.html
exit